name: tasks_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.0
  isar: ^3.0.5
  go_router: ^13.2.4
  google_fonts: ^4.0.3
  http: ^1.2.1
  shared_preferences: ^2.0.18
  formz: ^0.7.0
  image_picker: ^1.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/T.png"
    
